module.exports = (stateID) => {
  let column = [];
  switch (stateID) {
    case '7':
      column = [
        //Gujarat
        'Applicant First Name *',
        'Applicant Last Name *',
        'Application No *',
        'Applicant Mobile No',
        'Applicant Email Id',
        'Is Applicant/Owner Same ? *',
        'Owner Name *',
        'State *',
        'Base Document Type *',
        'District *',
        'Taluka',
        'Village',
        'PropertyType  *',
        'PropertyAddress *',
        'Survey No',
        'TP No',
        'FP No',
        'Khata No',
        'City Survey Office',
        'Ward',
        'City Survey No',
        'Building/Block/Shed/Flat No',
        'Socity Name',
        'Type Of Loan *',
        'Loan Amount *',
        'Is There Known Lien on Property? *',
        'Lien Person Name',
        'Lien From',
        'Lien Amount',
        'Lien Date',
      ];
      break;
    case '12':
      column = [
        //Karnataka
        'Applicant First Name *',
        'Applicant Last Name *',
        'Application No *',
        'Applicant Mobile No',
        'Applicant Email Id',
        'Is Applicant/Owner Same ? *',
        'Owner Name *',
        'State *',
        'Base Document Type *',
        'District * ',
        'Taluka *',
        'Hobli *',
        'Village *',
        'PropertyType *',
        'PropertyAddress *',
        'Survey No',
        'Hissa No',
        'Block',
        'Gram Panchayat',
        'Property ID',
        'Type Of Loan *',
        'Loan Amount *',
        'Is There Known Lien on Property? *',
        'Lien Person Name',
        'Lien From',
        'Lien Amount',
        'Lien Date',
      ];
      break;
    case '15':
      column = [
        //Maharashtra
        'Applicant First Name *',
        'Applicant Last Name *',
        'Application No *',
        'Applicant Mobile No',
        'Applicant Email Id',
        'Is Applicant/Owner Same ? *',
        'Owner Name *',
        'State *',
        'Base Document Type *',
        'District *',
        'Taluka *',
        'Village *',
        'PropertyType *',
        'PropertyAddress *',
        'Survey / Gat No',
        'Hissa No/Sub Division No',
        'Khata No',
        'Region (Vibhag)',
        'City Survey Office',
        'City Survey No',
        'Building/Block/Shed/Flat No',
        'Society Name',
        'Type Of Loan *',
        'Loan Amount *',
        'Is There Known Lien on Property? *',
        'Lien Person Name',
        'Lien From',
        'Lien Amount',
        'Lien Date'
      ];
      break;
    case '22':
      column = [
        //Rajashthan
        'Applicant First Name *',
        'Applicant Last Name *',
        'Application No *',
        'Applicant Mobile No',
        'Applicant Email Id ',
        'Is Applicant/Owner Same ? *',
        'Owner Name *',
        'State *',
        'Base Document Type *',
        'District *',
        'Tehsil *',
        'Village *',
        'PropertyType *',
        'PropertyAddress *',
        'Khasra No',
        'Khata No',
        'Building/Block/Shed/Flat No',
        'Socity Name',
        'Type Of Loan *',
        'Loan Amount *',
        'Is There Known Lien on Property? *',
        'Lien Person Name',
        'Lien From',
        'Lien Amount',
        'Lien Date',
      ];
      break;
    case '24':
      column = [
        //Tamilnadu
        'Applicant First Name *',
        'Applicant Last Name *',
        'Application No *',
        'Applicant Mobile No',
        'Applicant Email Id ',
        'Is Applicant/Owner Same ? *',
        'Owner Name *',
        'State *',
        'Base Document Type *',
        'District *',
        'Taluka *',
        'Village',
        'Town',
        'Ward',
        'Block',
        'PropertyType  *',
        'PropertyAddress *',
        'Survey No *',
        'Sub Division No',
        'Patta Number',
        'Building/Block/Shed/Flat No',
        'Society Name',
        'Type Of Loan  *',
        'Loan Amount *',
        'Is There Known Lien on Property? *',
        'Lien Person Name',
        'Lien From',
        'Lien Amount',
        'Lien Date',
      ];
      break;
  
    case '25':
      column = [
        //Telangana
        'Applicant First Name *',
        'Applicant Last Name *',
        'Application No *',
        'Applicant Mobile No',
        'Applicant Email Id ',
        'Is Applicant/Owner Same ? *',
        'Owner Name *',
        'State *',
        'Base Document Type *',
        'District *',
        'Mandal *',
        'Village *',
        'Survey No/Sub Division No *',
        'Khata No *',
        "ULB",
        "PTIN NO",
        "Door No",
        "Circle",
        'PropertyType  *',
        'PropertyAddress *',
        'Building/Block/Shed/Flat No',
        'Society Name',
        'Type Of Loan  *',
        'Loan Amount *',
        'Is There Known Lien on Property? *',
        'Lien Person Name',
        'Lien From',
        'Lien Amount',
        'Lien Date',
      ];
      break;
  }
  return column;
};
